# Change these first
owner: ArtieFuzzz # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.astolfo.cafe
  # baseUrl: /your-repo-name
  name: "Artie's Status Page"
  introTitle: "Artie's Status Page"
  theme: night
  introMessage: This page is updated in Real-Time
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
